name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: repo

    steps:
      - uses: actions/checkout@v6
        with:
          path: repo
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - run: dotnet restore ./FortniteReplayDecompressor.slnx --force
      - run: dotnet build ./FortniteReplayDecompressor.slnx --configuration Release -p:RestoreForce=true -p:ImportProjectExtensionProps=false
      - run: dotnet test ./FortniteReplayDecompressor.slnx --coverage --report-github -p:ImportProjectExtensionProps=false
